### ISSUE TITLE
Admin stats

### ISSUE THREAD

**Issue by xpelanek** [adaptive-learning/flocs#103]
The site should contain "admin" sections with some statistics - this is very useful for catching bugs and unintended behavior, and also for determining priorities for further development (e.g. addition of new tasks).

Task statistics (sortable table?), for each task:
  * number of time solved
  * solving time (median)
  * evaluation stats
  * concepts used

User stats (per day):
  * number of users / solved tasks 
  * average evaluation

Other: survival analysis, ...

**Comment by effa** [comment]
Statistics for blocks: in which tasks, cost, how many people earned the block.

**Comment by effa** [comment]
Tasks += median of number of attempts

Users - possibility to select interval length (day vs. week...)

Table for concepts: for each concept, number of tasks with this concept, how many people know the concept, how many solved task instances with this concept

Session - average length, average ration of solved tasks (vs. given up), number of unfinished sessions
