### ISSUE TITLE
Filter task in respect to available blocks

### ISSUE THREAD

**Issue by jcechak** [adaptive-learning/flocs#145]
Consider only tasks that do not require blocks not owned by the student. Namely before intelligent task selector kicks in. 

Check must be made even when student visits exact task URL. Think of what should be the best thing to do in such situation. Should we allow the student to solve the task with temporary access to new blocks (possibly without any effect on his/her skill and credits) or strictly deny access to such task?

**Comment by effa** [comment]
Filtering implemented. Currently it applies for all selectors, but we might want to implement some more friendly behavior for IdSpecfiedSelector to let the student attempt any task (possibly in a special "non-game" mode).
