### ISSUE TITLE
Make awesome task completion modal

### ISSUE THREAD

**Issue by jirmauritz** [adaptive-learning/flocs#190]
- visualize new gained block
- visualize gained credits in progress bar

**Comment by effa** [comment]
- add time percentil (together with speed-meter - see user stats)
- use icons instead of tons of texts

**Comment by effa** [comment]
Resolved by d4c7b7693ca954b109b5b8aae6f92b455f03c3e4 and bb8092207dd57581564ab38c3d9ee0a6125f861a.
