### ISSUE TITLE
Complete interactive instructions

### ISSUE THREAD

**Issue by jirmauritz** [adaptive-learning/flocs#69]
- instructions for other things than concepts (block limit)
- more interactive and non-ignorable instructions (like google pop-ups)

**Comment by effa** [comment]
Non-ignorable: the instructions tab will be open at the beginning of solving and you can open them anywhere.

Interactive: at least a screenshot and ideally live demo. (We can also explore the possibility of *work examples* (skeletons).)

**Comment by effa** [comment]
Basic version of interactive non-ignorable mini-instructions done.
