### ISSUE TITLE
User statistics

### ISSUE THREAD

**Issue by xpelanek** [adaptive-learning/flocs#73]
User statistics: which many problems did I solve - their difficulty, my self-evaluation, my time, covered concepts, ...

**Comment by effa** [comment]
Information about credits, my earned blocks and blocks I can get soon and how many credits I need for the.

**Comment by effa** [comment]
Basic user statistics are implemented (blocks and tasks). Other ideas for user statistics page are captured by issues #178, #179, #180 and #181.
