### ISSUE TITLE
Problem text: title, instructions

### ISSUE THREAD

**Issue by xpelanek** [adaptive-learning/flocs#74]
Title for each problems (looks nice + may be useful for statistics).

Instructions are repetitive, it is hard to notice new features in the text. Proposal:
 * separate texts into individual "mini-instructions"
 * always show only "mini-instructions" relevat to particular problem (can be done automatically?)
 * highlight "new" instruction (which the user did not see before)

**Comment by effa** [comment]
Titles added in commits 2496187b0c6a56765c82b7b0d7496242b58c7007, 1a30362e8c55562f67aa0e32b2e01c52ef7fe439 and 522b4d28bf078e24d6ee1cb0f34ece27296e70fd.

**Comment by effa** [comment]
Basic version of interactive non-ignorable mini-instructions done.
