### ISSUE TITLE
Proper user authentication

### ISSUE THREAD

**Issue by effa** [adaptive-learning/flocs#78]
* refactoring (best practices, unify names (e.g. login vs. user at frontend) locations matching module names (flocs.user should not be in directory register), etc. etc. etc.)
* allow authentication via Google account (OAuth)
* lazy user not to force users to log in immediately

**Comment by effa** [comment]
+ explicit forcing of logged / staff user (and DRY exception handling if the user is not logged (/staff,...)

**Comment by jcechak** [comment]
- User backend and frontend has been refactored.
- User login and permissions are now explicitely enforced before making a transition to the state/url. Dry execution is handled by displaying error pages.
- Related commits are 8b9ebc7, 97576af, a80d6a6, 1a78a8f, 1e96705 and 0ea85e0.
