### ISSUE TITLE
New concepts: maze, sequence, variables, functions

### ISSUE THREAD

**Issue by effa** [adaptive-learning/flocs#83]
Introduce these concepts, including their "microinstructions", update and extend tests which works with concepts. Also make sure that modules are as independent on specific concepts as possible (e.g. instead of listing all concepts, use one of prepared enumeration of concepts).

**Comment by effa** [comment]
Another possible game concept: block limit

**Comment by jirmauritz** [comment]
Mostly done. New issue for functions created.
